EHgrab version 2.0! See CHANGELOG

diff --git a/ehgrab b/ehgrab
--- a/ehgrab
+++ b/ehgrab
@@ -1,193 +1,303 @@
-#! /bin/sh
+#!/bin/bash
+########################################################################################################################
+# EHgrab                                                                                                               #
+# Version 2.0                                                                                                          #
+#                                                                                                                      #
+# A shell script for automatically downloading image galleries from E-Hentai (https://e-hentai.org).                   #
+# See README.md for additional details.                                                                                #
+#                                                                                                                      #
+# Copyright 2016-2018 "Cacoethic Cavalier" <code@cacoethiccavalier.com>                                                #
+#                                                                                                                      #
+# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with  #
+# the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0                      #
+#                                                                                                                      #
+# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on  #
+# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the   #
+# specific language governing permissions and limitations under the License.                                           #
+########################################################################################################################
 
-# displays a usage message to standard err and exit with an exit code of 1
-show_usage()
-{
-    echo "usage: $1 src_url [dest]" 1>&2
-    exit 1
+usage="Usage: ehgrab [OPTION]... URL [DIR]"
+gethelp="Try 'ehgrab --help' for more information."
+imgnum=1
+
+# error out with usage message if at least one argument isn't provided 
+[[ $# -eq 0 ]] && echo -e "$usage\n$gethelp" >&2 && exit 1
+
+# define debug level output
+if [[ $@ == *"--debug"* ]]; then
+    debug=1
+    exec 3>&1
+else
+    exec 3>/dev/null
+fi
+
+########################################################################################################################
+#                                                       Functions                                                      #
+########################################################################################################################
+
+# given a webpage's content, get only the links, on their own lines
+isolateLinks() {
+    # separate links onto their own lines
+    sed "s;<a ;\n&;g" |
+    sed "s;</a>;&\n;g" |
+    # select only lines with links
+    grep "</a>"
 }
 
-# gets the main image from the current page in high quality, or standard quality if high quality is not accessible.
-download_image()
-{
-    # get URL for the standard quality image
-    URL="$(
-        # get current page's content
-        echo "$CUR_PAGE" |
-        # seperate images onto their own lines
+# given an anchor tag, get only the URL
+isolateURL() {
+    sed "s;<a.*href=\";;" |
+    sed "s;\".*;;"
+}
+
+downloadImage() {
+    # get the URL of the standard definition image
+    # (unfortunately, we need to do this for either case, to get the file extension)
+    echo -e "\tExtracting standard definition image URL from page..." >&3
+    url="$(
+        echo $current_page_content |
+        # separate images onto their own lines
         sed "s;<img;\n&;g" |
-        sed "s;/>;&\n;g" |
+        sed "s;>;&\n;g" |
         # select only lines with images
         grep "<img" |
-        # select only images with style (only main image is styled)
+        # isolate the main image (FRAGILE)
         grep "style" |
-        # isolate the image source URL
+        # isolate the src URL
         sed "s;.*src=\";;" |
         sed "s;\".*;;"
     )"
+    echo -e "\tExtracted URL: $url" >&3
 
-    # create the path for the file
-    FILE_PATH="$DEST/$(printf "%04d" "$FILE_NUM")$(echo "$URL" | sed "s;.*\.;\.;")"
+    # generate the file name
+    echo -e "\tGenerating file name..." >&3
+    filename="$(printf "%04d" "$imgnum")$(echo $url | sed "s;.*\.;\.;")"
+    echo -e "\tGenerated file name: $filename" >&3
 
-    # if SKIP_HQ is set or there is no higher quality image available
-    if [ "$SKIP_HQ" -eq 0 -o "$(echo "$CUR_PAGE" | grep "Download original" | wc -l)" -eq 0 ]; then
-        # get the standard quality image
-        curl -s "$URL" > "$FILE_PATH"
-    else
-        # get current page's content
-        echo "$CUR_PAGE" |
-        # seperate links onto their own lines
-        sed "s;<a;\n&;g" |
-        sed "s;</a>;&\n;g" |
-        # select only lines with links
-        grep "<a" |
-        # isolate the original file link
+    # get the image
+    if [[ -z $sd && $(echo "$current_page_content)" | grep "Download original") ]]; then
+        echo -e "\tDownloading of high definition images enabled, and high definition image available:" >&3
+        echo -e "\tDownloading high definition image" >&3
+
+        echo $current_page_content |
+        isolateLinks |
+        # isolate original file link (FRAGILE)
         grep "Download original" |
-        # isolate the link URL
-        sed "s;<a.*href=\";;" |
-        sed "s;\".*;;" |
-        # get rid of the amp; codes after the ampersands
-        sed "s|amp;||g" |
-        # get the high quality image
-        xargs curl -sL --cookie "ipb_member_id=$EHUSR; ipb_pass_hash=$EHPWD" > "$FILE_PATH"
-    fi
-
-    # iterate the file number
-    let "FILE_NUM += 1"
-}
-
-# sets CUR_PAGE to the next page's content. If on the last page, sets CUR_PAGE to the current page's content (no change)
-get_next_page()
-{
-    CUR_PAGE="$(
-        # get current page's content
-        echo "$CUR_PAGE" |
-        # seperate links onto their own lines
-        sed "s;<a;\n&;g" |
-        sed "s;</a>;&\n;g" |
-        # select only lines with links
-        grep "<a" |
-        # isolate links with the "next" image inside
-        grep "n\.png" |
-        # isolate the link URL
-        sed "s;<a.*href=\";;" |
-        sed "s;\".*;;" |
-        # get only one (link repeats due to nav appearing at the top and bottom)
-        head -1 |
-        # get the next page's content
-        xargs curl -s
-    )"
-}
-
-# returns 0 if the current page is the last page, else returns 1
-is_last_page()
-{
-    PAGE_NUM_CUR_AND_LAST="$(
-        # get current page content
-        echo "$CUR_PAGE" |
-        # seperate spans onto their own lines (spans contain current page number and last page number)
-        sed "s;<span>;\n&;g" |
-        sed "s;</span>;&\n;g" |
-        # select only lines with spans
-        grep "<span>" |
-        # isolate span content (page numbers)
-        sed "s;<span>;;" |
-        sed "s;</span>;;" |
-        # get only first two (both numbers repeat due to nav appearing at the top and bottom)
-        head -2
-    )"
-
-    # get the current page number (first line)
-    PAGE_NUM_CUR="$(echo "$PAGE_NUM_CUR_AND_LAST" | head -1)"
-    # get the last page number (last line)
-    PAGE_NUM_LAST="$(echo "$PAGE_NUM_CUR_AND_LAST" | tail -1)"
-
-    if [ "$PAGE_NUM_CUR" == "$PAGE_NUM_LAST" ]; then
-        return 0
+        isolateURL |
+        # remove the "amp;" codes after the ampersands, leaving just the ampersands
+        sed "s;amp\;;;g" |
+        # get the file (FRAGILE)
+        xargs curl -sL --cookie "ipb_member_id=$userid; ipb_pass_hash=$passh" > "$path/$filename"
     else
-        return 1
+        echo -e "\tDownloading standard definition image" >&3
+        curl -s $url > "$path/$filename"
     fi
 }
 
-########################################################################################################################
+getNextPage() {
+    previous_page=$current_page
+    current_page=$(
+        echo "$current_page_content" |
+        isolateLinks |
+        # isolate links with the "next" image inside (FRAGILE)
+        grep "n\.png" |
+        isolateURL |
+        # get only one (multiple links remain due to multiple nav groups)
+        head -1
+    )
+    current_page_content=$(curl -s $current_page)
+}
 
-SKIP_HQ=1
-FILE_NUM=0001
-DONE=1
+################################################################################
 
-########################################################################################################################
+# parse arguments
 
-# check for the correct number of arguments
-if [ "$#" -lt 1 -o "$#" -gt 2 ]; then
-    show_usage $0
-fi
-
-# if a destination is provided as an argument, use that as DEST
-if [ "$#" -eq 2 ]; then
-    DEST="$2"
-# else check for a $EHDEST environment variable and use that if available
-elif [ -n "$EHDEST" ]; then
-    DEST="$EHDEST"
-# else no destination was provided; exit with failure code
-else
-    echo "No destination provided and no \$EHDEST environment variable set. Exiting." 1>&2
-    exit 2
-fi
-
-# make destination directory if it doesn't exist
-ls "$DEST" &> /dev/null
-if [ $? -ne 0 ]; then
-    mkdir -p "$DEST"
-fi
-
-# normalize destination filepath
-DEST="$(realpath $DEST)"
-
-# check if E-Hentai username and password environment variables are set, and set SKIP_HQ if they are not
-if   [ -z "$EHUSR" -a -n "$EHPWD" ]; then
-    echo "Warning: No E-Hentai user ID set. Both \$EHUSR and \$EHPWD environment variables must be set to download" \
-         "high quality images. High quality images, where available, will not be downloaded. Standard quality will" \
-         "be downloaded instead." 1>&2
-    SKIP_HQ=0
-elif [ -n "$EHUSR" -a -z "$EHPWD" ]; then
-    echo "Warning: No E-Hentai password hash set. Both \$EHUSR and \$EHPWD environment variables must be set to" \
-         "download high quality images. High quality images, where available, will not be downloaded. Standard" \
-         "quality will be downloaded instead." 1>&2
-    SKIP_HQ=0
-elif [ -z "$EHUSR" -a -z "$EHPWD" ]; then
-    echo "Warning: No E-Hentai user ID or password hash set. Both \$EHUSR and \$EHPWD environment variables must be" \
-         "set to download high quality images. High quality images, where available, will not be downloaded. Standard" \
-         "quality will be downloaded instead." 1>&2
-    SKIP_HQ=0
-fi
-
-# get the content of the first page from the gallery page
-CUR_PAGE="$(
-    # get gallery page's content
-    curl -s $1 |
-    # seperate links onto their own lines
-    sed "s;<a;\n&;g" |
-    sed "s;</a>;&\n;g" |
-    # select only lines with links
-    grep "<a" |
-    # isolate the first thumbnail
-    grep "alt=\"0*1\"" |
-    # isolate the link URL
-    sed "s;<a.*href=\";;" |
-    sed "s;\">.*;;" |
-    # get the first page's content
-    xargs curl -s
-)"
-
-while : # infinite loop
-do
-    download_image
-
-    if is_last_page
-        then break
-    fi
-
-    get_next_page
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        -c|--config)
+            # specify a location in which to look for a config file for this script
+            echo "Config flag set: setting config file location to $2" >&3
+            [[ -n $2 && -f $2 ]] && config=$2
+            shift 2
+        ;;
+        --debug)
+            # debug is handled before other arguments, so just shift it out
+            shift
+        ;;
+        -h|--help)
+            echo "Help flag is set: displaying help and exiting" >&3
+            echo $usage
+            echo
+            echo "OPTIONS:"
+            printf "%-17s \t%s\n" "-c, --config FILE" \
+                   "Specify a path to a file to use as a configuration file (default ~/.ehgrab)"
+            printf "%-17s \t%s\n" "--debug" \
+                   "Enable verbose output for debugging"
+            printf "%-17s \t%s\n" "-h, --help" \
+                   "Display help"
+            printf "%-17s \t%s\n" "-p, --pass STRING" \
+                   "Specify a string to use as the password hash"
+            printf "%-17s \t%s\n" "-q, --quiet" \
+                   "Silence all output, including errors"
+            printf "%-17s \t%s\n" "--sd" \
+                   "Download only standard definition images, even if high definition images are available"
+            printf "%-17s \t%s\n" "-u, --user STRING" \
+                   "Specify a string to use as the user ID"
+            printf "%-17s \t%s\n" "-z, --zero" \
+                   "Start file names at 0000.extension (default 0001.extension)"
+            exit 0
+        ;;
+        -p|--pass)
+            # specify a password hash
+            echo "Pass flag is set: setting password hash to $2" >&3
+            [[ -n $2 ]] && passh=$2
+            shift 2
+        ;;
+        -q|--quiet)
+            echo "Quiet flag is set, but debug mode is active. Output will not be silenced." >&3
+            [[ -z $debug ]] && exec 1>/dev/null && exec 2>/dev/null
+            shift
+        ;;
+        --sd)
+            # force downloading of only standard definition images
+            echo "Standard definition flag is set: setting option to download only standard definition images" >&3
+            sd=1
+            shift
+        ;;
+        -u|--user)
+            # specify a user id
+            echo "User ID flag is set: setting user ID to $2" >&3
+            [[ -n $2 ]] && userid=$2
+            shift 2
+        ;;
+        -z|--zero)
+            # use zero-indexed file numbers
+            echo "Zero index flag is set: setting starting image number to 0000" >&3
+            imgnum=0
+            shift
+        ;;
+        *)
+            # the first argument without a flag preceding it is used as the source URL
+            if [[ -z $src ]]; then
+                echo "First argument not preceded by a flag: $1" >&3
+                echo "Setting source URL to $1" >&3
+                src=$1
+                shift
+            # the second argument without a flag preceding it is used as the destination path
+            elif [[ -z $path ]]; then
+                echo "Second argument not preceded by a flag: $1" >&3
+                echo "Setting destination path to $1" >&3
+                path=$1
+                shift
+            else
+            # additional arguments without a flag are ignored
+                echo "Ignoring additional argument not preceded by flag: $1" >&3
+                shift
+            fi
+    esac
 done
 
-exit 0
+echo >&3
+
+# error out if no source URL could be parsed
+[[ -z $src ]] && echo "Error: No source URL specified" >&2 && exit 1
+
+# use current directory as destination if no destination path could be parsed
+[[ -z $path ]] && path=. && echo "No destination path specified: using current directory as destination" >&3
+
+# make destination directory
+echo "Making destination directory" >&3
+mkdir -p $path && path=$(realpath $path)
+
+echo >&3
+
+# if no config file location was specified in the arguments, look in the default location of ~/.ehgrab
+echo "No config file specified: using ~/.ehgrab" >&3
+[[ -z "$config" ]] && config="$(realpath ~/.ehgrab)"
+# if the config file exists, then read variables from the config
+if [[ -f $config ]]; then
+    echo "Config file exists, reading..." >&3
+    while read line; do
+        value=$(echo "$line" | sed 's;^.*[ \t];;' )
+        case $(echo "$line" | sed 's;[ \t].*;;' ) in
+            user)
+                [[ -z $userid ]] && userid=$value && echo -e "\tSetting user ID to $value" >&3
+            ;;
+            pass)
+                [[ -z $passh ]] && passh=$value && echo -e "\tSetting password hash to $value" >&3
+            ;;
+        esac;
+    done < $config
+else
+    echo "Config file does not exist" >&2
+fi
+
+echo >&3
+
+# determine the starting location and get the first image page
+
+echo "Determining the starting location provided in the source URL..." >&3
+
+if [[ $src == *"e-hentai.org/g/"* ]]; then
+    # we were given a gallery page URL
+    echo "Source URL is a gallery page. Extracting first image page..." >&3
+    current_page=$(
+        # remove URL params to get the first gallery page
+        echo $src | sed "s;\?.*;;g" |
+        # get first gallery page's content
+        xargs curl -s |
+        isolateLinks |
+        # isolate the first thumbnail (FRAGILE)
+        grep "alt=\"0*1\"" |
+        isolateURL
+    )
+elif [[ $src == *"e-hentai.org/s"* ]]; then
+    # we were given an image page URL
+    echo "Source URL is an image page. Extracting first image page..." >&3
+    current_page=$(
+        # get all links from page
+        curl -s $src |
+        isolateLinks |
+        # isolate links with the "first" image inside (FRAGILE)
+        grep "f\.png" |
+        isolateURL |
+        # get only one (multiple links remain due to multiple nav groups)
+        head -1
+    )
+else
+    echo "Bad source URL" >&2
+    exit 1
+fi
+echo "First image page: $current_page" >&3
+
+echo >&3
+
+echo "Getting content of first image page..." >&3
+current_page_content=$(curl -s $current_page)
+
+echo >&3
+
+# check if we'll be attempting to get high quality images, and inform the user if not
+[[ -z $userid || -z $passh ]] && sd=1
+if [[ $sd ]]; then
+    if [[ -z $userid || -z $passh ]]; then
+        echo "User ID and/or password hash not provided: downloading only standard quality images"
+    else
+        echo "High quality image downloads disabled: downloading only standard quality images"
+    fi
+else 
+    echo "User ID and password hash provided, and high quality image downloads not disabled: " \
+         "will attempt to download high quality images" >&3
+fi
+
+echo >&3
+
+# download all the images
+while [[ $current_page != $previous_page ]]; do
+    echo "Downloading image $imgnum..."
+    downloadImage
+    echo "Getting next page..." >&3
+    getNextPage
+    let imgnum+=1
+done
+echo "Final page reached. Done!" >&3
